ui:
  image: jsm85/dockercomposesampleui
  links:
    - rabbit:rabbit
  ports:
    - "5001"
service:
  image: jsm85/dockercomposesampleservice
  links:
    - rabbit:rabbit
rabbit:
  image: "rabbitmq:3.6-management"
  ports:
    - "15672:15672"